---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data

```{r}
library(dplyr)
data <- read.csv("activity.csv",stringsAsFactors=FALSE)
data$date <- as.Date(data$date)
summary(data)
```


## What is mean total number of steps taken per day?

```{r}
daynames <- unique(data$date)
days <- group_by(data, date)
days <- summarise(days, nintervals=n(), avgsteps=mean(steps,na.rm=TRUE), totsteps=nintervals*avgsteps)
#days <- sapply(daynames, function(day) { sum(subset(data, date == day)$steps, na.rm=TRUE) })
plot(days$date, days$totsteps, type="h",xlab="Date",ylab="Total Steps per Day",main="Histogram - Total Number of Steps per Day")
```
 
 __Total Number of Steps per Day__  
 __Mean:__ `r mean(days$totsteps, na.rm=TRUE)`  
 __Median:__ `r median(days$totsteps, na.rm=TRUE)`  

## What is the average daily activity pattern?



## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
